<?php

namespace Database\Seeders\Exported;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExpenseTypesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('expense_types')->truncate();
        DB::table('expense_types')->insert([
            [
                'id' => 3,
                'name' => 'Pemeliharaan',
                'slug' => 'pemeliharaan',
                'description' => 'Belanja untuk pemeliharaan kendaraan, gedung, dan aset lainnya',
                'is_active' => 1,
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 08:07:41',
                'instansi_id' => 1,
            ],
            [
                'id' => 4,
                'name' => 'Makan dan Minum (Hotel)',
                'slug' => 'makan-minum-hotel',
                'description' => NULL,
                'is_active' => 1,
                'created_at' => '2025-12-20 16:47:59',
                'updated_at' => '2025-12-21 08:07:41',
                'instansi_id' => 1,
            ],
            [
                'id' => 5,
                'name' => 'Makan dan Minum (Katering)',
                'slug' => 'makan-minum-katering',
                'description' => NULL,
                'is_active' => 1,
                'created_at' => '2025-12-20 16:48:19',
                'updated_at' => '2025-12-21 08:07:41',
                'instansi_id' => 1,
            ],
            [
                'id' => 6,
                'name' => 'Perjalanan Dinas Dalam Daerah',
                'slug' => 'pdt-dalam-daerah',
                'description' => NULL,
                'is_active' => 1,
                'created_at' => '2025-12-20 18:08:05',
                'updated_at' => '2025-12-21 08:07:41',
                'instansi_id' => 1,
            ],
            [
                'id' => 7,
                'name' => 'Perjalanan Dinas Luar Daerah',
                'slug' => 'pdt-luar-daerah',
                'description' => NULL,
                'is_active' => 1,
                'created_at' => '2025-12-20 18:08:06',
                'updated_at' => '2025-12-21 08:07:41',
                'instansi_id' => 1,
            ],
            [
                'id' => 8,
                'name' => 'SPJ RUTIN',
                'slug' => 'spj-rutin',
                'description' => 'SPJ Rutin (Gaji, Tunjangan, BPJS, Air, Pajak, Honor)',
                'is_active' => 1,
                'created_at' => '2026-01-14 04:23:58',
                'updated_at' => '2026-01-14 04:23:58',
                'instansi_id' => NULL,
            ],
            [
                'id' => 9,
                'name' => 'SPJ BMHP',
                'slug' => 'spj-bmhp',
                'description' => 'SPJ Barang Milik Habis Pakai (ATK, Air Minum, Logistik, dll)',
                'is_active' => 1,
                'created_at' => '2026-01-14 04:23:58',
                'updated_at' => '2026-01-14 04:23:58',
                'instansi_id' => NULL,
            ],
            [
                'id' => 10,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-1',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:22',
                'updated_at' => '2026-03-22 14:52:22',
                'instansi_id' => 1,
            ],
            [
                'id' => 11,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-3',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:22',
                'updated_at' => '2026-03-22 14:52:22',
                'instansi_id' => 3,
            ],
            [
                'id' => 12,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-4',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 4,
            ],
            [
                'id' => 13,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-5',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 5,
            ],
            [
                'id' => 14,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-6',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 6,
            ],
            [
                'id' => 15,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-7',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 7,
            ],
            [
                'id' => 16,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-8',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 8,
            ],
            [
                'id' => 17,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-9',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 9,
            ],
            [
                'id' => 18,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-10',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 10,
            ],
            [
                'id' => 19,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-11',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 11,
            ],
            [
                'id' => 20,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-12',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 12,
            ],
            [
                'id' => 21,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-13',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 13,
            ],
            [
                'id' => 22,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-16',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 16,
            ],
            [
                'id' => 23,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-17',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 17,
            ],
            [
                'id' => 24,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-18',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 18,
            ],
            [
                'id' => 25,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-19',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 19,
            ],
            [
                'id' => 26,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-20',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 20,
            ],
            [
                'id' => 27,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-21',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 21,
            ],
            [
                'id' => 28,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-22',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 22,
            ],
            [
                'id' => 29,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-23',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 23,
            ],
            [
                'id' => 30,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-24',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 24,
            ],
            [
                'id' => 31,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-25',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 25,
            ],
            [
                'id' => 32,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-26',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 26,
            ],
            [
                'id' => 33,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-27',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 23,
            ],
            [
                'id' => 34,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-28',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 28,
            ],
            [
                'id' => 35,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-29',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 29,
            ],
            [
                'id' => 36,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-30',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 30,
            ],
            [
                'id' => 37,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-31',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 31,
            ],
            [
                'id' => 38,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-32',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 32,
            ],
            [
                'id' => 39,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-33',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 33,
            ],
            [
                'id' => 40,
                'name' => 'Belanja Pegawai',
                'slug' => 'belanja-pegawai-34',
                'description' => 'Jenis pengeluaran untuk Belanja Pegawai',
                'is_active' => 1,
                'created_at' => '2026-03-22 14:52:23',
                'updated_at' => '2026-03-22 14:52:23',
                'instansi_id' => 34,
            ],
            [
                'id' => 41,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-1',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 1,
            ],
            [
                'id' => 42,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-3',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 3,
            ],
            [
                'id' => 43,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-4',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 4,
            ],
            [
                'id' => 44,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-5',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 5,
            ],
            [
                'id' => 45,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-6',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 6,
            ],
            [
                'id' => 46,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-7',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 7,
            ],
            [
                'id' => 47,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-8',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 8,
            ],
            [
                'id' => 48,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-9',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 9,
            ],
            [
                'id' => 49,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-10',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 10,
            ],
            [
                'id' => 50,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-11',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 11,
            ],
            [
                'id' => 51,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-12',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 12,
            ],
            [
                'id' => 52,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-13',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 13,
            ],
            [
                'id' => 53,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-16',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 16,
            ],
            [
                'id' => 54,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-17',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 17,
            ],
            [
                'id' => 55,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-18',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 18,
            ],
            [
                'id' => 56,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-19',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 19,
            ],
            [
                'id' => 57,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-20',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 20,
            ],
            [
                'id' => 58,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-21',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 21,
            ],
            [
                'id' => 59,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-22',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 22,
            ],
            [
                'id' => 60,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-23',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 23,
            ],
            [
                'id' => 61,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-24',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 24,
            ],
            [
                'id' => 62,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-25',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 25,
            ],
            [
                'id' => 63,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-26',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 26,
            ],
            [
                'id' => 64,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-27',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 23,
            ],
            [
                'id' => 65,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-28',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 28,
            ],
            [
                'id' => 66,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-29',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 29,
            ],
            [
                'id' => 67,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-30',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 30,
            ],
            [
                'id' => 68,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-31',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 31,
            ],
            [
                'id' => 69,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-32',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 32,
            ],
            [
                'id' => 70,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-33',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 33,
            ],
            [
                'id' => 71,
                'name' => 'Barang dan Jasa',
                'slug' => 'pengeluaran-barang-jasa-34',
                'description' => 'Jenis pengeluaran untuk pembelian barang dan jasa',
                'is_active' => 1,
                'created_at' => '2026-03-29 03:33:19',
                'updated_at' => '2026-03-29 03:34:55',
                'instansi_id' => 34,
            ],
        ]);
    }
}
