<?php

namespace Database\Seeders\Exported;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PegawaisSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pegawais')->truncate();
        DB::table('pegawais')->insert([
            [
                'id' => 1,
                'nama' => 'RUDY HARTONO S.STP, M.Si.',
                'nip' => '197702231996121001',
                'pangkat' => 'Pembina Tingkat I',
                'golongan' => 'IV/b',
                'jabatan' => 'CAMAT',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 2,
                'nama' => 'SONI PERMANA',
                'nip' => '196911141994031006',
                'pangkat' => 'Penata Muda Tingkat I',
                'golongan' => 'III/b',
                'jabatan' => 'PENGOLAH DATA DAN INFORMASI',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 3,
                'nama' => 'RULI TARSIDI S.Sos.',
                'nip' => '197005122007011014',
                'pangkat' => 'Penata',
                'golongan' => 'III/c',
                'jabatan' => 'KEPALA SUBBAGIAN',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 4,
                'nama' => 'LIA YULIANA S.Sos., M.Si',
                'nip' => '197407032007012007',
                'pangkat' => 'Pembina',
                'golongan' => 'IV/a',
                'jabatan' => 'KEPALA SEKSI',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 5,
                'nama' => 'BENI TAUFIK S.AP',
                'nip' => '198406042010011010',
                'pangkat' => 'Penata Muda Tingkat I',
                'golongan' => 'III/b',
                'jabatan' => 'KEPALA SEKSI',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 6,
                'nama' => 'ATI HARTATI S.Sos',
                'nip' => '197610062007012007',
                'pangkat' => 'Penata',
                'golongan' => 'III/c',
                'jabatan' => 'PENELAAH TEKNIS KEBIJAKAN',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 7,
                'nama' => 'BABAM NURJAMAN SE',
                'nip' => '197007132007011009',
                'pangkat' => 'Pembina',
                'golongan' => 'IV/a',
                'jabatan' => 'SEKRETARIS - KECAMATAN',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 8,
                'nama' => 'YAHYA',
                'nip' => '197003292008011002',
                'pangkat' => 'Pengatur',
                'golongan' => 'II/c',
                'jabatan' => 'PENGOLAH DATA DAN INFORMASI',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 9,
                'nama' => 'SITI NOVIYANTI S.Sos., M.K.P',
                'nip' => '198304042010012001',
                'pangkat' => 'Penata Tingkat I',
                'golongan' => 'III/d',
                'jabatan' => 'KEPALA SEKSI',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 10,
                'nama' => 'RENY YULIA S.H., M.Si.',
                'nip' => '197208082010012002',
                'pangkat' => 'Penata Tingkat I',
                'golongan' => 'III/d',
                'jabatan' => 'KEPALA SEKSI',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 11,
                'nama' => 'HARI SUMARHADI S.A.P.',
                'nip' => '198102242014101001',
                'pangkat' => 'Penata Muda',
                'golongan' => 'III/a',
                'jabatan' => 'KEPALA SUBBAGIAN',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 12,
                'nama' => 'RAHMAT HIDAYAT S.H.',
                'nip' => '197510282007011006',
                'pangkat' => 'Penata Muda Tingkat I',
                'golongan' => 'III/b',
                'jabatan' => 'KEPALA SEKSI',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 13,
                'nama' => 'DIAN AKHMAD RIFQI A.Md.',
                'nip' => '199209092020121001',
                'pangkat' => 'Pengatur Tingkat I',
                'golongan' => 'II/d',
                'jabatan' => 'PENGOLAH DATA DAN INFORMASI',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 14,
                'nama' => 'MAYANG KUSUMA NARIYAH A.Md.Kom.',
                'nip' => '199605252020122002',
                'pangkat' => 'Pengatur Tingkat I',
                'golongan' => 'II/d',
                'jabatan' => 'PENGOLAH DATA DAN INFORMASI',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 15,
                'nama' => 'FAHMI TAUFIK FIRDAUS A.Md.',
                'nip' => '199512112024211004',
                'pangkat' => '-',
                'golongan' => 'VII',
                'jabatan' => 'ARSIPARIS TERAMPIL',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
            [
                'id' => 16,
                'nama' => 'DIDIK KURNIAWAN ST',
                'nip' => '199412012025051003',
                'pangkat' => 'Penata Muda',
                'golongan' => 'III/a',
                'jabatan' => 'PENATA KELOLA SISTEM DAN TEKNOLOGI INFORMASI',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2026-03-22 14:15:32',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => 'pegawai/perjanjian-kinerja/01KMAYDBBHAFZRCTDEAQFVHPJJ.pdf',
            ],
            [
                'id' => 17,
                'nama' => 'RD. AGUS HAMZAH',
                'nip' => '197208082025211004',
                'pangkat' => '-',
                'golongan' => 'V',
                'jabatan' => 'OPERATOR LAYANAN OPERASIONAL',
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2025-12-21 07:54:59',
                'instansi_id' => 1,
                'peran' => NULL,
                'file_perjanjian_kinerja' => NULL,
            ],
        ]);
    }
}
