<?php

namespace Database\Seeders\Exported;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->truncate();
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Administrator',
                'email' => 'admin@kencana.test',
                'phone_number' => '082130314252',
                'email_verified_at' => NULL,
                'password' => '$2y$12$sJuw0O6PNSX3NjdBuxfWuuPNMSMV6jc.L91OxJ/SCIS2dVRnZWtwu',
                'remember_token' => NULL,
                'created_at' => '2025-12-19 12:54:56',
                'updated_at' => '2026-03-30 09:03:46',
            ],
            [
                'id' => 8,
                'name' => 'Bendahara',
                'email' => 'bendahara@test.com',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$ijjtcIB2qJWepqpQYdEoKeKv9jqYfvvmQGyz/RuGBQDJlvxrKkAEG',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 10:38:03',
                'updated_at' => '2026-03-31 15:14:55',
            ],
            [
                'id' => 11,
                'name' => 'Operator',
                'email' => 'operator@test.com',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$t3sGOR5NgOU6bIkvUKMc1OgMFevxUDmh5FvYim00SjKs18o.7doJy',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 11:43:45',
                'updated_at' => '2026-03-31 15:14:55',
            ],
            [
                'id' => 12,
                'name' => 'Verifikator',
                'email' => 'verifikator@test.com',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$pTetvkqMoFoau.bSseZw1OLuV/vI95GZSIjv0kwXrjYnfBn4jbZFS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 11:43:45',
                'updated_at' => '2026-03-31 15:14:55',
            ],
            [
                'id' => 13,
                'name' => 'Pimpinan',
                'email' => 'pimpinan@test.com',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$wh.YNe.2fC/lEPIXe0hFJ.Gs6Kpz90Ve0LTI./QTY7evBthIumQ2O',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 11:43:46',
                'updated_at' => '2026-03-31 15:14:55',
            ],
            [
                'id' => 14,
                'name' => 'Cangkuang - Admin Instansi',
                'email' => '320444.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$goRHtXZNhY5s/gH.mREGnOB50pUbkDFsgM.hVxnDQcM7y8YpqRKEa',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:54',
                'updated_at' => '2026-03-30 17:31:24',
            ],
            [
                'id' => 15,
                'name' => 'Cangkuang - Operator',
                'email' => '320444.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$pdi0vuk4Sdkzr.IhtGttSOrJ2608oO/KmQJVliIaU2egM5eIMWpia',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:54',
                'updated_at' => '2026-03-30 17:31:24',
            ],
            [
                'id' => 16,
                'name' => 'Cangkuang - Verifikator',
                'email' => '320444.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$v9VBpeqaBHIs8DHJXgBV1.Qfj5XMZvP1eyKFPJm27tfh7htXaeJd.',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:54',
                'updated_at' => '2026-03-30 17:31:25',
            ],
            [
                'id' => 17,
                'name' => 'Cangkuang - Pimpinan',
                'email' => '320444.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$ioE02HEF.FOzIihBC9Ei0ebX4D6/OIB4tOviVvbTK.9uDB34BrDAe',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:55',
                'updated_at' => '2026-03-30 17:31:25',
            ],
            [
                'id' => 18,
                'name' => 'Cangkuang - Bendahara',
                'email' => '320444.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$1x.KFjiRtoBrxxU73hHU/.lYEnOadigrM6XCQxzOqoYthVBYP2MD.',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:55',
                'updated_at' => '2026-03-30 17:31:25',
            ],
            [
                'id' => 19,
                'name' => 'Ciwidey - Admin Instansi',
                'email' => '320420.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$spf2rrzraMbU1JxYMuL/ueX4jX.ISOGOPoldZtcmRTXdSehY0WnNK',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:56',
                'updated_at' => '2026-03-30 17:32:50',
            ],
            [
                'id' => 20,
                'name' => 'Ciwidey - Operator',
                'email' => '320420.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$8gTPbSggjbvTuiK/l.mvLuELTs/XbHRV4xp1CdesYoXmiPEJe4vCi',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:56',
                'updated_at' => '2026-03-30 17:32:50',
            ],
            [
                'id' => 21,
                'name' => 'Ciwidey - Verifikator',
                'email' => '320420.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Eno6IPuOX8EIdxkXhNU4qeUSP8F12Bi3I0GaZqMOzbS/0EpY5H7LG',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:56',
                'updated_at' => '2026-03-30 17:32:50',
            ],
            [
                'id' => 22,
                'name' => 'Ciwidey - Pimpinan',
                'email' => '320420.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$x3I1D1KjX4CbAPXLk.b49.eAUbSrptqJtS3BhPbbf1IrwOCvhUuzO',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:56',
                'updated_at' => '2026-03-30 17:32:51',
            ],
            [
                'id' => 23,
                'name' => 'Ciwidey - Bendahara',
                'email' => '320420.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Qm9LZJml4b/aTz97L60cBOMnAFp2r2bI13I5NJPlWiVDpVbMY.dAm',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:57',
                'updated_at' => '2026-03-30 17:32:51',
            ],
            [
                'id' => 24,
                'name' => 'Rancabali - Admin Instansi',
                'email' => '320442.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$aEs3WB0wRBoq7kkdcngozuS/I4Se8/fPQClhr5APSD5m/MmEuzaey',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:57',
                'updated_at' => '2026-03-30 17:31:27',
            ],
            [
                'id' => 25,
                'name' => 'Rancabali - Operator',
                'email' => '320442.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$PdvFMG4MNxJl9GxoyOg8xeADbofdro5660qxo/4he6oHp4deVtWgi',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:57',
                'updated_at' => '2026-03-30 17:31:27',
            ],
            [
                'id' => 26,
                'name' => 'Rancabali - Verifikator',
                'email' => '320442.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$tKwyOpi2mq9GsyAFTpCST.k5hpEqghGa3LK/zmOYgAxwAiabgcy/m',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:58',
                'updated_at' => '2026-03-30 17:31:28',
            ],
            [
                'id' => 27,
                'name' => 'Rancabali - Pimpinan',
                'email' => '320442.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$nTLRMhDiqGxioH/.0.Gpzu..0wz1iH06D1bD8M9ouMAGSb09YnCRy',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:58',
                'updated_at' => '2026-03-30 17:31:28',
            ],
            [
                'id' => 28,
                'name' => 'Rancabali - Bendahara',
                'email' => '320442.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$IkAVF75fR1Qt/3sPXChSG..j3zF.BaZvlqtkAUfaQs8IGROjcRcNy',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:58',
                'updated_at' => '2026-03-30 17:31:28',
            ],
            [
                'id' => 29,
                'name' => 'Pasirjambu - Admin Instansi',
                'email' => '320422.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$I6wnDlq9TeLoSRyit4FiLuQG0gDOa9TtBe3oOgsSo9rvO0mo.7Mpe',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:58',
                'updated_at' => '2026-03-30 17:31:29',
            ],
            [
                'id' => 30,
                'name' => 'Pasirjambu - Operator',
                'email' => '320422.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$hXkOxL3xY1YUjomBLnPw9.smuJhgQs5Q5wiG.6hub4CdJyhY5v/Au',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:59',
                'updated_at' => '2026-03-30 17:31:29',
            ],
            [
                'id' => 31,
                'name' => 'Pasirjambu - Verifikator',
                'email' => '320422.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4SoUzq6evZjrVx8B.ZvhsOCx.xlDYdmyPZwA0Wk4Bq7Nl.AJLsRHS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:59',
                'updated_at' => '2026-03-30 17:31:29',
            ],
            [
                'id' => 32,
                'name' => 'Pasirjambu - Pimpinan',
                'email' => '320422.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$NCEitM2Cv6Fg/50SzYToeeLCsHUqGkOFChquBfslz45mpIPqEmvJG',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:24:59',
                'updated_at' => '2026-03-30 17:31:30',
            ],
            [
                'id' => 33,
                'name' => 'Pasirjambu - Bendahara',
                'email' => '320422.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$X9ZrpO7dRjlZcPeSh.i7z.Qyuf4P9AOEtJoXPHOOnMgaj9k1rBUK6',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:00',
                'updated_at' => '2026-03-30 17:31:30',
            ],
            [
                'id' => 34,
                'name' => 'Cimaung - Admin Instansi',
                'email' => '320423.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4LD1yHhhrlCdB33YZdFfVuO7kUc.IudZ0iQcbbphAzlotNaCsBHlW',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:00',
                'updated_at' => '2026-03-30 17:31:30',
            ],
            [
                'id' => 35,
                'name' => 'Cimaung - Operator',
                'email' => '320423.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$dJQogabviCeQxbfr.9MeuuCIHk9X06A4wx/hiysKdxyHg2C5R2YhO',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:00',
                'updated_at' => '2026-03-30 17:31:30',
            ],
            [
                'id' => 36,
                'name' => 'Cimaung - Verifikator',
                'email' => '320423.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$eTTQQeD.pDuFoVkXnIxuw.DVGJkYgtcnkBCjNAwwKRTf6ZKEzm5Ka',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:00',
                'updated_at' => '2026-03-30 17:31:31',
            ],
            [
                'id' => 37,
                'name' => 'Cimaung - Pimpinan',
                'email' => '320423.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$r8oIdNC4B/0xJ./AeRMmBObtPm02eICnSmgWxrqb.1bT.Yx6WEOwS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:01',
                'updated_at' => '2026-03-30 17:31:31',
            ],
            [
                'id' => 38,
                'name' => 'Cimaung - Bendahara',
                'email' => '320423.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$RDwTBz8JEK66tnoqUmaWEOCypk4jd8d3SNpyCWMvjvy2kUKra4UT.',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:01',
                'updated_at' => '2026-03-30 17:31:32',
            ],
            [
                'id' => 39,
                'name' => 'Pangalengan - Admin Instansi',
                'email' => '320418.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Gmyd1WlWTT7WYdOr2mTA9uz27zll4rysVtgybktRp9WDcmszyRGVO',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:01',
                'updated_at' => '2026-03-30 17:31:32',
            ],
            [
                'id' => 40,
                'name' => 'Pangalengan - Operator',
                'email' => '320418.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$GH1c1MgY9f2CHLMguE/tdu0iOiitxX.WwCuLY4OzTTmCdPhRcSMh.',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:02',
                'updated_at' => '2026-03-30 17:31:33',
            ],
            [
                'id' => 41,
                'name' => 'Pangalengan - Verifikator',
                'email' => '320418.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$GVpiTqYxaWLKWGUkkrlBvO1KCkw1tin.KoNqEYj9JjWHrJqsyk2Fm',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:02',
                'updated_at' => '2026-03-30 17:31:33',
            ],
            [
                'id' => 42,
                'name' => 'Pangalengan - Pimpinan',
                'email' => '320418.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$0J7hJfBqQDxfuMPnMdfCzObi9MWbdr43SzWxC6RllNnmFI40Drzhy',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:02',
                'updated_at' => '2026-03-30 17:31:33',
            ],
            [
                'id' => 43,
                'name' => 'Pangalengan - Bendahara',
                'email' => '320418.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$k9CTdQs3ou92lRgQ5PZkP.0XvEiDxpX.1PVzrG4lYRc6ltCt.wpGK',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:03',
                'updated_at' => '2026-03-30 17:31:33',
            ],
            [
                'id' => 44,
                'name' => 'Kertasari - Admin Instansi',
                'email' => '320435.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$eaVbZtb6Zh0SIakjxFqVS.OK.k7B71lr4vNPUeQhE44Pj2oaoTjGK',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:03',
                'updated_at' => '2026-03-30 17:31:34',
            ],
            [
                'id' => 45,
                'name' => 'Kertasari - Operator',
                'email' => '320435.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$c3BZpYMiTr0s8NPJbwuBperPs7lKOX2Cq3ahyKu8z1nStezumfMfe',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:03',
                'updated_at' => '2026-03-30 17:31:34',
            ],
            [
                'id' => 46,
                'name' => 'Kertasari - Verifikator',
                'email' => '320435.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$lzlGbNW04uzjEplbPylqaeKBrY/zI7h158FVJjH0F4SVZq9Mu9Ru.',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:03',
                'updated_at' => '2026-03-30 17:31:34',
            ],
            [
                'id' => 47,
                'name' => 'Kertasari - Pimpinan',
                'email' => '320435.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$QIdnQYpJWADKOIrjuXKQg.mMVy/OqlfKAg3dXrIA9Vgn/8lC0DBqa',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:04',
                'updated_at' => '2026-03-30 17:31:35',
            ],
            [
                'id' => 48,
                'name' => 'Kertasari - Bendahara',
                'email' => '320435.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$RaYkkDWAm8jgM63dMOirtux4BJxR3xi1buSwpccBxZUN2ZGep0o6e',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:04',
                'updated_at' => '2026-03-30 17:31:35',
            ],
            [
                'id' => 49,
                'name' => 'Pacet - Admin Instansi',
                'email' => '320430.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$14/h.4ZuktsqHJnXO6kZyOAHanLAMYZ2ybivOrialsSsisfQeuO2O',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:04',
                'updated_at' => '2026-03-30 17:31:35',
            ],
            [
                'id' => 50,
                'name' => 'Pacet - Operator',
                'email' => '320430.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$n4QlUpoYTUhrDE1OasfE3uDw2wmGBh/uSyuvCKqa0LJ0n8xkycM62',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:05',
                'updated_at' => '2026-03-30 17:31:36',
            ],
            [
                'id' => 51,
                'name' => 'Pacet - Verifikator',
                'email' => '320430.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Zv790ELZgidC3m6dHNnS4ufNfeBfIkv0oAQ0HPuMcnS0F99ziHLGu',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:05',
                'updated_at' => '2026-03-30 17:31:36',
            ],
            [
                'id' => 52,
                'name' => 'Pacet - Pimpinan',
                'email' => '320430.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$aeO4s4Y1QrtUQ15T/Cl27O4zKeH4yEiZlACdRvykOvuts.jT7YgbC',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:05',
                'updated_at' => '2026-03-30 17:31:36',
            ],
            [
                'id' => 53,
                'name' => 'Pacet - Bendahara',
                'email' => '320430.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$PgtmCrK0OjItKM1p.YoYce2WNtB.rQROfE3OPZlIqyreOyoRNRHla',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:05',
                'updated_at' => '2026-03-30 17:31:36',
            ],
            [
                'id' => 54,
                'name' => 'Ciparay - Admin Instansi',
                'email' => '320426.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$OaYp1hz64leE0oS.rrwIhOfCJ4wQWlqJ9QLjc/UDBYyYAwoCQ7n0C',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:06',
                'updated_at' => '2026-03-30 17:31:37',
            ],
            [
                'id' => 55,
                'name' => 'Ciparay - Operator',
                'email' => '320426.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$FsZXCfZNJvF3bl5Bt3kv0eYxVw7aaZ2h/AcawezUMmGm3jtK2D8ce',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:06',
                'updated_at' => '2026-03-30 17:31:37',
            ],
            [
                'id' => 56,
                'name' => 'Ciparay - Verifikator',
                'email' => '320426.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$M3HLNMCkX8pnhNvRQqfrBOmxUAe73a21zn6.eu0Iq/mRlWfslp47u',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:06',
                'updated_at' => '2026-03-30 17:31:37',
            ],
            [
                'id' => 57,
                'name' => 'Ciparay - Pimpinan',
                'email' => '320426.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$GKKk00RwjZqz.kKtwkDM6e1.ZotqFPyDYsqzDgdmfgoin8BiDhcaG',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:06',
                'updated_at' => '2026-03-30 17:31:38',
            ],
            [
                'id' => 58,
                'name' => 'Ciparay - Bendahara',
                'email' => '320426.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4rTgxSoxnAogr514xALGquVVdD9qXV3W6kAcMGEvyrzocqJNj4BZG',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:07',
                'updated_at' => '2026-03-30 17:31:38',
            ],
            [
                'id' => 59,
                'name' => 'Baleendah - Admin Instansi',
                'email' => '320432.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$bkEnDxdxjhNCWDZ64TZig.Zt3cMXUN7vyd0BdjsNC2kKSTLE/577G',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:07',
                'updated_at' => '2026-03-30 17:31:38',
            ],
            [
                'id' => 60,
                'name' => 'Baleendah - Operator',
                'email' => '320432.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$6Luk3DPLPh8j6/WMyfZioOkJa59WMyqd7L3l0QSi9Fe7bZUo1AbRa',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:07',
                'updated_at' => '2026-03-30 17:31:39',
            ],
            [
                'id' => 61,
                'name' => 'Baleendah - Verifikator',
                'email' => '320432.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$MAM9P0yUNByMiXOO0xBiQ.2mJNCG4uwrkmgZGljuD8WMj9yfw7vAS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:08',
                'updated_at' => '2026-03-30 17:31:39',
            ],
            [
                'id' => 62,
                'name' => 'Baleendah - Pimpinan',
                'email' => '320432.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$vCfC4O1o7G3JQ40qru2Rx.WBTGVRiufWosJbTLSFS/yr303xqSqBS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:08',
                'updated_at' => '2026-03-30 17:31:39',
            ],
            [
                'id' => 63,
                'name' => 'Baleendah - Bendahara',
                'email' => '320432.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$OBM9ekJpQprTn5SYqRH8h.ne7Z21ORGFhnwNe86NEU79SkO72jA92',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:08',
                'updated_at' => '2026-03-30 17:31:39',
            ],
            [
                'id' => 64,
                'name' => 'Arjasari - Admin Instansi',
                'email' => '320416.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$tjBXy/OUCjknu.bhqwI0ZezD6u/ilJDvGsXfvCNTp3icjOtapab3y',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:09',
                'updated_at' => '2026-03-30 17:31:40',
            ],
            [
                'id' => 65,
                'name' => 'Arjasari - Operator',
                'email' => '320416.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$izasHGBZH3JHAEUj9MScyekuIgeL35DXpQJvIy3qPjAjdmjCJEmuq',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:09',
                'updated_at' => '2026-03-30 17:31:40',
            ],
            [
                'id' => 66,
                'name' => 'Arjasari - Verifikator',
                'email' => '320416.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$f77X37qsX5o6ZgYKTYP3Ke4Msa/3EAM85LhJVLaYuYEjs9UaBzU9C',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:09',
                'updated_at' => '2026-03-30 17:31:40',
            ],
            [
                'id' => 67,
                'name' => 'Arjasari - Pimpinan',
                'email' => '320416.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$KJbiekkwsjFGZoZ4SQdW3OMRwc7ct69.axrGfZkNEm2kjcLtTlfwi',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:09',
                'updated_at' => '2026-03-30 17:31:41',
            ],
            [
                'id' => 68,
                'name' => 'Arjasari - Bendahara',
                'email' => '320416.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$m8iW8D42n4E2oTwtcqoxLe3NfiqCd8YZF.Gy2kPVBmagfj2zHeobW',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:10',
                'updated_at' => '2026-03-30 17:31:41',
            ],
            [
                'id' => 69,
                'name' => 'Banjaran - Admin Instansi',
                'email' => '320413.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$iQ1yFwGaLB6z/QBeNYFHt.Byh/Lhdbs15jAp8dMsHK1vKJB7p3j6y',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:10',
                'updated_at' => '2026-03-30 17:31:41',
            ],
            [
                'id' => 70,
                'name' => 'Banjaran - Operator',
                'email' => '320413.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$AJiju9jcyzWGtf3tbQ5q3.EN73.AWkDeBlP5Efyv1VQqlvEtUHMoa',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:10',
                'updated_at' => '2026-03-30 17:31:41',
            ],
            [
                'id' => 71,
                'name' => 'Banjaran - Verifikator',
                'email' => '320413.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$TJgdJrml5h/KETH5H.A3uugkDkD5PhdOT84I80ceG2XZ9b./C9/0y',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:11',
                'updated_at' => '2026-03-30 17:31:42',
            ],
            [
                'id' => 72,
                'name' => 'Banjaran - Pimpinan',
                'email' => '320413.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$v77OwJIFm3Q7rCzNrg4lW.EaXgwG9D4H6KeRb0bw2ZUjG08Zs6U6K',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:11',
                'updated_at' => '2026-03-30 17:31:42',
            ],
            [
                'id' => 73,
                'name' => 'Banjaran - Bendahara',
                'email' => '320413.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$SF7gy9FXeKEkJkcaxIhKO.L5DK4VjQxj8RKlSC2SQNpTIRwykdsdi',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:11',
                'updated_at' => '2026-03-30 17:31:42',
            ],
            [
                'id' => 74,
                'name' => 'Pameungpeuk - Admin Instansi',
                'email' => '320433.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$xNsn0GQSZyoWD0d.arEh5etH7qwYqJvJMqaZ7yH9QS7wi02kiHk4.',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:11',
                'updated_at' => '2026-03-30 17:31:43',
            ],
            [
                'id' => 75,
                'name' => 'Pameungpeuk - Operator',
                'email' => '320433.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$6yM0wZSa3xNO/0ToVQ2Oz.DAIlmJXAurqLTNxxbykYOx/87VCcAKi',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:12',
                'updated_at' => '2026-03-30 17:31:43',
            ],
            [
                'id' => 76,
                'name' => 'Pameungpeuk - Verifikator',
                'email' => '320433.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$MTQaImF6pWyAHOvffWo01.TSZUsA1uY/3T1clgjzSQOQ2HkU7e0Ui',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:12',
                'updated_at' => '2026-03-30 17:31:43',
            ],
            [
                'id' => 77,
                'name' => 'Pameungpeuk - Pimpinan',
                'email' => '320433.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$8RNXOdSVlbcPhtJL2yKc6umtHk0p5muyzGb6HboljFZOOH5yWKNUW',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:12',
                'updated_at' => '2026-03-30 17:31:44',
            ],
            [
                'id' => 78,
                'name' => 'Pameungpeuk - Bendahara',
                'email' => '320433.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$qVsKdZgoiHNeHj4zKqRPNOgFxJ/axjz8t9rwJQ487ECkIkdUiJivK',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:12',
                'updated_at' => '2026-03-30 17:31:44',
            ],
            [
                'id' => 79,
                'name' => 'Katapang - Admin Instansi',
                'email' => '320411.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$rHkdtl44Pq.vHusVMZBYR.srLoG/MXFj9m26zBofk0m/Dnf1rj05.',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:13',
                'updated_at' => '2026-03-30 17:31:45',
            ],
            [
                'id' => 80,
                'name' => 'Katapang - Operator',
                'email' => '320411.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$XsKeZ7/iNK/UoseNGpMH7e.t9yNOggpQ1JmcH8tQwuBMHzgOUeuWu',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:13',
                'updated_at' => '2026-03-30 17:31:45',
            ],
            [
                'id' => 81,
                'name' => 'Katapang - Verifikator',
                'email' => '320411.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$wKl.KQHgn8pPGqnbsSs7BuEm7YQUTVB28TuoME5X5uKvITov5hPEq',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:13',
                'updated_at' => '2026-03-30 17:31:46',
            ],
            [
                'id' => 82,
                'name' => 'Katapang - Pimpinan',
                'email' => '320411.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$euQfheSg.Y4HVNjwDIk4G.9WXKuGL0rT8SAVlha3BhNcor473H.pO',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:14',
                'updated_at' => '2026-03-30 17:31:46',
            ],
            [
                'id' => 83,
                'name' => 'Katapang - Bendahara',
                'email' => '320411.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$K.b7Cr361OJ9vRY3MGlpSuZyxcYWdbyxqHBzY01Afr0HMpOgiekB6',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:14',
                'updated_at' => '2026-03-30 17:31:46',
            ],
            [
                'id' => 84,
                'name' => 'Soreang - Admin Instansi',
                'email' => '320437.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$88TZMmTEMwCTNdNdCRT6UuH/7XAU7rJJ7RuF5OHn3eNFHFFIfcg0W',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:14',
                'updated_at' => '2026-03-30 17:31:47',
            ],
            [
                'id' => 85,
                'name' => 'Soreang - Operator',
                'email' => '320437.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$dYjUWgWXRTx1mI3iqENSTe0WDTOkuT/5a4An8Hxc2emorXosnLnta',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:14',
                'updated_at' => '2026-03-30 17:31:47',
            ],
            [
                'id' => 86,
                'name' => 'Soreang - Verifikator',
                'email' => '320437.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$IvejohLX0Pg68seGGQyi..sq7wasLaJkxNPsiANTmr6PDrbliqIO6',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:15',
                'updated_at' => '2026-03-30 17:31:47',
            ],
            [
                'id' => 87,
                'name' => 'Soreang - Pimpinan',
                'email' => '320437.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$KZ2/ETHa.LlhjscDKx/is.N2uX/bs9SFtRgSc1vcdtijbp2iKbK8y',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:15',
                'updated_at' => '2026-03-30 17:31:48',
            ],
            [
                'id' => 88,
                'name' => 'Soreang - Bendahara',
                'email' => '320437.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$DLWHuCDK2ahOZwDHwQVY1etQP84t7dGY87pUcV6cM2rXINYO9y9Q.',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:15',
                'updated_at' => '2026-03-30 17:31:48',
            ],
            [
                'id' => 89,
                'name' => 'Kutawaringin - Admin Instansi',
                'email' => '320443.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$MYW46s.sd3GjYsD.QnLcPO9jFJGGJZ98Z696Toe97VyNNBkv3lDBq',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:15',
                'updated_at' => '2026-03-30 17:31:48',
            ],
            [
                'id' => 90,
                'name' => 'Kutawaringin - Operator',
                'email' => '320443.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$EAJXNntWmb0HcK2d4b3iweHd.oLc3DS/RGYwOES3ok9RMRxY42dS6',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:16',
                'updated_at' => '2026-03-30 17:31:48',
            ],
            [
                'id' => 91,
                'name' => 'Kutawaringin - Verifikator',
                'email' => '320443.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$03KRsYA1LtGtkdAAbN9s/uV5IqWm7CAFtlFsuRWMG43cXlbVaM2Oe',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:16',
                'updated_at' => '2026-03-30 17:31:49',
            ],
            [
                'id' => 92,
                'name' => 'Kutawaringin - Pimpinan',
                'email' => '320443.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$OilCybNVirzT/sAV61Gz0OzqYja7dcRB9M9/a8joMFVw4Jd7dHg7i',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:16',
                'updated_at' => '2026-03-30 17:31:49',
            ],
            [
                'id' => 93,
                'name' => 'Kutawaringin - Bendahara',
                'email' => '320443.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$SUDnVO5L9qVX1CWfR5qcNuDXXPB4x7wx45zgtFTjsEUe9pEDpNI1i',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:17',
                'updated_at' => '2026-03-30 17:31:49',
            ],
            [
                'id' => 94,
                'name' => 'Margaasih - Admin Instansi',
                'email' => '320410.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$2j5k1SVfLytN7lBhQB7hlOUjCEgZ58XWvNsJvW3x4FAW/NZRY..EK',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:17',
                'updated_at' => '2026-03-30 17:31:49',
            ],
            [
                'id' => 95,
                'name' => 'Margaasih - Operator',
                'email' => '320410.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$njE2Epq6lzOyKOa8NjuGNupQfG4VF34/R9tQD9ZAFvXiaTuOxsi6i',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:17',
                'updated_at' => '2026-03-30 17:31:50',
            ],
            [
                'id' => 96,
                'name' => 'Margaasih - Verifikator',
                'email' => '320410.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$3ECgyj5rvwLK2I/PV/J6aeXuy4ZeBq4uHS2BhvsrPo.Vi9A0G3kUO',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:17',
                'updated_at' => '2026-03-30 17:31:50',
            ],
            [
                'id' => 97,
                'name' => 'Margaasih - Pimpinan',
                'email' => '320410.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$n5l.Bt.Kd1gDVQ/kgJX20ecQKynba6.OPrZEQE1xBIgCWKp1Chyje',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:18',
                'updated_at' => '2026-03-30 17:31:50',
            ],
            [
                'id' => 98,
                'name' => 'Margaasih - Bendahara',
                'email' => '320410.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$UYi5Ii1zu2W3S1ULVx9MQe.Oipb1nsjRr9TiU2zypHRCjtIEF4qi2',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:18',
                'updated_at' => '2026-03-30 17:31:51',
            ],
            [
                'id' => 99,
                'name' => 'Margahayu - Admin Instansi',
                'email' => '320412.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$RSqnuW/nmTXvsmFI6p4N4ensUfIq1uJ/gxBoOlCitaSCfXCQGKTKS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:18',
                'updated_at' => '2026-03-30 17:31:51',
            ],
            [
                'id' => 100,
                'name' => 'Margahayu - Operator',
                'email' => '320412.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$9E9XGeR9l2gCint3XI6f9eC/ABzb.SI3TJqW5pZwknN.L1Ea/odAO',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:18',
                'updated_at' => '2026-03-30 17:31:51',
            ],
            [
                'id' => 101,
                'name' => 'Margahayu - Verifikator',
                'email' => '320412.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$BWsCoOGtjg.wHkbeddj.7ufOK//Q56s89F/XQpiLh5AeKvpl8lxhu',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:19',
                'updated_at' => '2026-03-30 17:31:51',
            ],
            [
                'id' => 102,
                'name' => 'Margahayu - Pimpinan',
                'email' => '320412.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Cw.sKLTU07uhu6CCsqrH5.pUdM/tbNB/JMCJESJSw1lueCYYDBVPW',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:19',
                'updated_at' => '2026-03-30 17:31:52',
            ],
            [
                'id' => 103,
                'name' => 'Margahayu - Bendahara',
                'email' => '320412.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$YhcwvWli4iopnJZPfNmCPeX0AzFAF/aipsmsC2nUYekkGdau2pi.S',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:19',
                'updated_at' => '2026-03-30 17:31:52',
            ],
            [
                'id' => 104,
                'name' => 'Dayeuhkolot - Admin Instansi',
                'email' => '320409.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$r8jaI37fXEHzlIbTcd3M1e3imrI8.SdqNtGHQbMK5cd3BE.YwzqKC',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:20',
                'updated_at' => '2026-03-30 17:31:52',
            ],
            [
                'id' => 105,
                'name' => 'Dayeuhkolot - Operator',
                'email' => '320409.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$U6XZK1L/OlpDz30MouW/cu1Xj959BUZDx/6c4gUtAPhejKcyabf2G',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:20',
                'updated_at' => '2026-03-30 17:31:53',
            ],
            [
                'id' => 106,
                'name' => 'Dayeuhkolot - Verifikator',
                'email' => '320409.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$MU7uRLClNI1SXFhHP3UCPu6RktnlNCQcafVU.xiaueceT8zMBQ4Ei',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:20',
                'updated_at' => '2026-03-30 17:31:53',
            ],
            [
                'id' => 107,
                'name' => 'Dayeuhkolot - Pimpinan',
                'email' => '320409.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4c7m.qtiXKlAIiC69bDquuv9pvQ.xCst7PQAzMjkiXcE.MJbGojtO',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:20',
                'updated_at' => '2026-03-30 17:31:53',
            ],
            [
                'id' => 108,
                'name' => 'Dayeuhkolot - Bendahara',
                'email' => '320409.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$K9avwWMx/ZF7sVE0r.alXOd6qSD3cB3ID/1ABjVS8aKDQE0ZSDd1i',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:21',
                'updated_at' => '2026-03-30 17:31:54',
            ],
            [
                'id' => 109,
                'name' => 'Bojongsoang - Admin Instansi',
                'email' => '320408.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$zo0lGI8GEz/8SodkFZvW.OWFVL8fpvNmmw8mXE41c/Npdw9oSIKkS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:21',
                'updated_at' => '2026-03-30 17:31:54',
            ],
            [
                'id' => 110,
                'name' => 'Bojongsoang - Operator',
                'email' => '320408.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$ZFQ9PvW5q.W9XzzNs.wxpefHgoc0rITMfPngmlpXP/thcGYwtVru.',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:21',
                'updated_at' => '2026-03-30 17:31:54',
            ],
            [
                'id' => 111,
                'name' => 'Bojongsoang - Verifikator',
                'email' => '320408.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$pBOSlyMSDL7tJnRoZipdtugND859UwEGGtFFviMli0RgdkUFrIoby',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:22',
                'updated_at' => '2026-03-30 17:31:54',
            ],
            [
                'id' => 112,
                'name' => 'Bojongsoang - Pimpinan',
                'email' => '320408.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$A2XhOaX82LC4P2.QX894dOj1gS4oDQcU7oyMrRAI3rjxp3Gwv3qwi',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:22',
                'updated_at' => '2026-03-30 17:31:55',
            ],
            [
                'id' => 113,
                'name' => 'Bojongsoang - Bendahara',
                'email' => '320408.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$25/sDnamVU8rLH.C8Am1I.TWyjah9bxHqR4FD9IUccaLmpZzwJ3Mm',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:22',
                'updated_at' => '2026-03-30 17:31:55',
            ],
            [
                'id' => 114,
                'name' => 'Cileunyi - Admin Instansi',
                'email' => '320406.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$d5N.zLtjexiRN3fPCh94ielywVjRELu6gIRBdfUwSsnlhM8wCdide',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:23',
                'updated_at' => '2026-03-30 17:31:55',
            ],
            [
                'id' => 115,
                'name' => 'Cileunyi - Operator',
                'email' => '320406.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$vQ5/sXHFboC4eCmZiki9feJf24qcrzMdjWO.Rfvjg.tj5I/JxspdS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:23',
                'updated_at' => '2026-03-30 17:31:55',
            ],
            [
                'id' => 116,
                'name' => 'Cileunyi - Verifikator',
                'email' => '320406.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$jPza3KkKq6i4TeGCHIq66eKQW63XH8C/66gOJXs5LJWTHdEzrBuiu',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:23',
                'updated_at' => '2026-03-30 17:31:56',
            ],
            [
                'id' => 117,
                'name' => 'Cileunyi - Pimpinan',
                'email' => '320406.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$US7VnDP7KFk215F1KtWxJOh4qsVyHPb1f2CFkTNixr3UnpXCFtfmq',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:23',
                'updated_at' => '2026-03-30 17:31:56',
            ],
            [
                'id' => 118,
                'name' => 'Cileunyi - Bendahara',
                'email' => '320406.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$AFW4y1JoKCHOBjrMWvpoH.H24PINjdYwTb/dkE2erQoCFWMXmE2tm',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:24',
                'updated_at' => '2026-03-30 17:31:56',
            ],
            [
                'id' => 119,
                'name' => 'Cilengkrang - Admin Instansi',
                'email' => '320407.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$0ytltwujqojWOG8q6cjCyOI6KGV4I1SmO.03/mrmvG.TS8W19C/My',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:24',
                'updated_at' => '2026-03-30 17:31:57',
            ],
            [
                'id' => 120,
                'name' => 'Cilengkrang - Operator',
                'email' => '320407.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$yR81ntwG3HheOc/rvwXL8u2t262jguAnCjLMkTRqhJcyQGj0vFSHy',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:24',
                'updated_at' => '2026-03-30 17:31:57',
            ],
            [
                'id' => 121,
                'name' => 'Cilengkrang - Verifikator',
                'email' => '320407.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$NpgLQ44bhPA9jUqu3pHb4eMZh1xLaiKAFkroHR1xw7qRHtT/tNsna',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:24',
                'updated_at' => '2026-03-30 17:31:57',
            ],
            [
                'id' => 122,
                'name' => 'Cilengkrang - Pimpinan',
                'email' => '320407.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Hy3/P/i5pQlOx4nQT1d2iu85jFIDq9Jwvs2n270kXJ0YxzdfDGpOy',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:25',
                'updated_at' => '2026-03-30 17:31:57',
            ],
            [
                'id' => 123,
                'name' => 'Cilengkrang - Bendahara',
                'email' => '320407.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$6sTggOw7TM9IGqaGpkboG..0q040937.dD8VtD6h1MDLJjxztvEzG',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:25',
                'updated_at' => '2026-03-30 17:31:58',
            ],
            [
                'id' => 124,
                'name' => 'Cimenyan - Admin Instansi',
                'email' => '320405.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$6Tdm/j7WfIqsnzYhJmYltecg0DicOMm41HockBLUAkGJwtFznmV8O',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:25',
                'updated_at' => '2026-03-30 17:31:58',
            ],
            [
                'id' => 125,
                'name' => 'Cimenyan - Operator',
                'email' => '320405.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$8Pc5j0QAg1wVUXDZLgAq7eFFGyl0/QBfAh4qPg9RwqEqY/f7cuZfq',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:26',
                'updated_at' => '2026-03-30 17:31:58',
            ],
            [
                'id' => 126,
                'name' => 'Cimenyan - Verifikator',
                'email' => '320405.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$/32PL7DhWVg70J26QajHP.SkBSnEyYvuPdyrTL0LHOHf7Jec.Uc6.',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:26',
                'updated_at' => '2026-03-30 17:31:59',
            ],
            [
                'id' => 127,
                'name' => 'Cimenyan - Pimpinan',
                'email' => '320405.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4TZeX7N6TORTdN5m7SgyzOA0bSdV3fzsOkwo2lxKw7ZmakFJJxIIC',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:26',
                'updated_at' => '2026-03-30 17:31:59',
            ],
            [
                'id' => 128,
                'name' => 'Cimenyan - Bendahara',
                'email' => '320405.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$TcHlv9raJVB8dBAHoQUDKeHD0rtaR.ymgeTtA5WdIcJPtUOMEEBzO',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:26',
                'updated_at' => '2026-03-30 17:31:59',
            ],
            [
                'id' => 129,
                'name' => 'Rancaekek - Admin Instansi',
                'email' => '320424.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$rS9wE/0mdyjLbIwhahQSAOSMtdkG5ZiVCNorFiPzZVzlBhCuBZjwC',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:27',
                'updated_at' => '2026-03-30 17:32:00',
            ],
            [
                'id' => 130,
                'name' => 'Rancaekek - Operator',
                'email' => '320424.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$/7sxZAv0.y1Fuwb8eAYt3OMNcxt5lUDLHu3nRPuFrspkjhDJLxS7y',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:27',
                'updated_at' => '2026-03-30 17:32:00',
            ],
            [
                'id' => 131,
                'name' => 'Rancaekek - Verifikator',
                'email' => '320424.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$.58Y/BFjjg3oKya86O5tveP0MmKvHSEy0sNE356bpR.b7lAk5wF0a',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:27',
                'updated_at' => '2026-03-30 17:32:00',
            ],
            [
                'id' => 132,
                'name' => 'Rancaekek - Pimpinan',
                'email' => '320424.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$K5WpW5tn25Kksxw9zEta3.0rX1.vC7/SMfGoJA88XmJSlolAABmom',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:27',
                'updated_at' => '2026-03-30 17:32:00',
            ],
            [
                'id' => 133,
                'name' => 'Rancaekek - Bendahara',
                'email' => '320424.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$JjI7kida7gQp8Yb/0ljsxeEm1CJPaYSP/uDzVWtUPHHJc2ERUSd3u',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:28',
                'updated_at' => '2026-03-30 17:32:01',
            ],
            [
                'id' => 134,
                'name' => 'Nagreg - Admin Instansi',
                'email' => '320428.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$9GIeO1sP0.rNLL5iUBiyIuZxCHpEwqsBGQcjZyDWvSypMgPfSdH46',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:28',
                'updated_at' => '2026-03-30 17:32:01',
            ],
            [
                'id' => 135,
                'name' => 'Nagreg - Operator',
                'email' => '320428.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$u77xuqcdmJtVuHABAWE.jOGhJDBOUlT2PjgbA0crjnlyXYio2q0ZG',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:28',
                'updated_at' => '2026-03-30 17:32:01',
            ],
            [
                'id' => 136,
                'name' => 'Nagreg - Verifikator',
                'email' => '320428.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$u.bnjn2TmnkHs9K5Vkf04OVGqe/LDphvXEPLTsA0l9E9E52QVPfn2',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:29',
                'updated_at' => '2026-03-30 17:32:01',
            ],
            [
                'id' => 137,
                'name' => 'Nagreg - Pimpinan',
                'email' => '320428.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$rjZBVJn2vL13r1RkYHITFuH90W8xNVtlUGaU/B3vyd4gIH/B8boqC',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:29',
                'updated_at' => '2026-03-30 17:32:02',
            ],
            [
                'id' => 138,
                'name' => 'Nagreg - Bendahara',
                'email' => '320428.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$qRx11cl7F6gOa4VnD4xB/eILdA1Mgj9VAu3PVedXqnKKgMyuT2gIS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:29',
                'updated_at' => '2026-03-30 17:32:02',
            ],
            [
                'id' => 139,
                'name' => 'Cicalengka - Admin Instansi',
                'email' => '320425.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$NBriIRfF9/tgnwLoCFlRjuGr.zZgNNt8UreGkk4qrBMmS7m/bNXiy',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:29',
                'updated_at' => '2026-03-30 17:32:02',
            ],
            [
                'id' => 140,
                'name' => 'Cicalengka - Operator',
                'email' => '320425.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$G2ERWgUsvWpWkzG1KHSe7O025Pm2uzGl/OoKsDzXpC.HkPyFWUHLG',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:30',
                'updated_at' => '2026-03-30 17:32:03',
            ],
            [
                'id' => 141,
                'name' => 'Cicalengka - Verifikator',
                'email' => '320425.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$XmyxJQMbMqBvrN2NUpuWc.5wnw0dBWI/C4V.3jy6OKj/SIfIYlIOq',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:30',
                'updated_at' => '2026-03-30 17:32:03',
            ],
            [
                'id' => 142,
                'name' => 'Cicalengka - Pimpinan',
                'email' => '320425.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$mN.i3aIpVK7f1RAXbNvT1..42cPwPKn5zqBVd1J/zV0.bv5Qdwvty',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:30',
                'updated_at' => '2026-03-30 17:32:03',
            ],
            [
                'id' => 143,
                'name' => 'Cicalengka - Bendahara',
                'email' => '320425.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$wSkwjPbv3uIEMoHaKgcvwuEVMG238NkLkvCnl3d3PT0ULp0UMN8ue',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:31',
                'updated_at' => '2026-03-30 17:32:03',
            ],
            [
                'id' => 144,
                'name' => 'Cikancung - Admin Instansi',
                'email' => '320427.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$qducd5.pGqAZ.QvR8PC1D.xsIp6Byu05xWuemPSElWo7/8NTIgOu6',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:31',
                'updated_at' => '2026-03-30 17:32:04',
            ],
            [
                'id' => 145,
                'name' => 'Cikancung - Operator',
                'email' => '320427.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$jNrqfxlx6f3d9/UaHgs55OCAUVy5qaEmx6IzecSr14Rm6bSf9Rc76',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:31',
                'updated_at' => '2026-03-30 17:32:04',
            ],
            [
                'id' => 146,
                'name' => 'Cikancung - Verifikator',
                'email' => '320427.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$entOJP2d4UfxYQPlaGx/dehNPOMyQLNBli5FUS8xX7QxFwojQR8PG',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:31',
                'updated_at' => '2026-03-30 17:32:04',
            ],
            [
                'id' => 147,
                'name' => 'Cikancung - Pimpinan',
                'email' => '320427.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Ykgj9QC1QPdoR6BF/O9K0eOAb9krUJSGMCAxPRAGpUxFIw2qjdjvK',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:32',
                'updated_at' => '2026-03-30 17:32:04',
            ],
            [
                'id' => 148,
                'name' => 'Cikancung - Bendahara',
                'email' => '320427.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$vvMpzdm4ZDnZffjgwJg6bubz.zknzXW.SSpnMLmxys7r9w/DEeFLK',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:32',
                'updated_at' => '2026-03-30 17:32:05',
            ],
            [
                'id' => 149,
                'name' => 'Majalaya - Admin Instansi',
                'email' => '320415.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$EQkE/rxKtKtWbH24s.fKXeOwZ8YqlA/yNkWzRlwnGtXvdgE6//iBi',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:32',
                'updated_at' => '2026-03-30 17:32:05',
            ],
            [
                'id' => 150,
                'name' => 'Majalaya - Operator',
                'email' => '320415.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$0y7tts2ONTK44vNeY760KemOh.xE04UfIjGPNaeqmv1VHEPAlra2e',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:32',
                'updated_at' => '2026-03-30 17:32:05',
            ],
            [
                'id' => 151,
                'name' => 'Majalaya - Verifikator',
                'email' => '320415.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$hEiGEJtG.X9eUfxu03zivOfaYQEXI4E5SgYTNaNaV91aaej4oddfO',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:33',
                'updated_at' => '2026-03-30 17:32:06',
            ],
            [
                'id' => 152,
                'name' => 'Majalaya - Pimpinan',
                'email' => '320415.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$jvV5dKn9arxSyRCcOtrfKecxAjSf5ApYmC2fSTfdimSgSmSWHQs.S',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:33',
                'updated_at' => '2026-03-30 17:32:06',
            ],
            [
                'id' => 153,
                'name' => 'Majalaya - Bendahara',
                'email' => '320415.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$5xzJcCYVxQXAr5u5GZYD9.Mosb7G9Rf.BRj17wSQ1nRgwF5vHgEhW',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:33',
                'updated_at' => '2026-03-30 17:32:06',
            ],
            [
                'id' => 154,
                'name' => 'Solokanjeruk - Admin Instansi',
                'email' => '320434.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$4CEED/Yer2FFmMXjG/RG0OS1RY2DjY4xw3mfX9egORspxTTVExaj6',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:34',
                'updated_at' => '2026-03-30 17:32:06',
            ],
            [
                'id' => 155,
                'name' => 'Solokanjeruk - Operator',
                'email' => '320434.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$LY1l0t3G0cah9SQ.SYxxB.3i1OfkiGc3HqYADqLOp4lM9DN139O4m',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:34',
                'updated_at' => '2026-03-30 17:32:07',
            ],
            [
                'id' => 156,
                'name' => 'Solokanjeruk - Verifikator',
                'email' => '320434.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Jq0/yc.DpY2Zcgvs48DWSeRMrUaLUL.kqxs/BguUsFopXgWlG1cd2',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:34',
                'updated_at' => '2026-03-30 17:32:07',
            ],
            [
                'id' => 157,
                'name' => 'Solokanjeruk - Pimpinan',
                'email' => '320434.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$1BgCc13JzSDFNYIAJlqM6e3G3jc88925ekGjAnVhyGueauLBn/Uk6',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:34',
                'updated_at' => '2026-03-30 17:32:07',
            ],
            [
                'id' => 158,
                'name' => 'Solokanjeruk - Bendahara',
                'email' => '320434.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$X0/a3nLbpKQRdoBv2VjEA.BIsfIoz5VuAsH7FI5dgv8Nxv7lmsUXm',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:35',
                'updated_at' => '2026-03-30 17:32:07',
            ],
            [
                'id' => 159,
                'name' => 'Ibun - Admin Instansi',
                'email' => '320431.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$EMFXl/KE.BRfPGCXNK8aX.mWVoQFKcPlaB3JLzuQJw4g3J1MWsDlS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:35',
                'updated_at' => '2026-03-30 17:32:08',
            ],
            [
                'id' => 160,
                'name' => 'Ibun - Operator',
                'email' => '320431.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$hQIh24pFxi2vrhxzKR.Akul4M0xWADXvwxupKi8qhewyZBggGm.5K',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:35',
                'updated_at' => '2026-03-30 17:32:08',
            ],
            [
                'id' => 161,
                'name' => 'Ibun - Verifikator',
                'email' => '320431.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$omN7dYwK1gmMwVHxPABKeuRyAH1LMhkPdCNtiyUtWL2pO4we0I2BS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:36',
                'updated_at' => '2026-03-30 17:32:08',
            ],
            [
                'id' => 162,
                'name' => 'Ibun - Pimpinan',
                'email' => '320431.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$VWNOBTpiLi2gtjuF9QnvzesLpVdFUpz0imm0/BZ2W.HA90.2KBiiy',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:36',
                'updated_at' => '2026-03-30 17:32:09',
            ],
            [
                'id' => 163,
                'name' => 'Ibun - Bendahara',
                'email' => '320431.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$pmvzCEwHlWscAKK3ErSeNOynvujmI5s1Vi/obhRhtCoG4wjJXfrey',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:36',
                'updated_at' => '2026-03-30 17:32:09',
            ],
            [
                'id' => 164,
                'name' => 'Paseh - Admin Instansi',
                'email' => '320429.admin_instansi@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$tdKkF1OED/uFxMbkQ6qKSOQ3XywvxbLIkSCW9rDqt9W4TFEY0ZcrS',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:37',
                'updated_at' => '2026-03-30 17:32:09',
            ],
            [
                'id' => 165,
                'name' => 'Paseh - Operator',
                'email' => '320429.operator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$euAsPZ8vCdNewlqVCs6g7uIUf98plj26JZbJpLiBkoJMygGWKYIpy',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:37',
                'updated_at' => '2026-03-30 17:32:09',
            ],
            [
                'id' => 166,
                'name' => 'Paseh - Verifikator',
                'email' => '320429.verifikator@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$vlxSapBP3RLIthnGYnGiOOR/reu6r0jZx.HDA8NAkfQujz2gSmCRW',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:37',
                'updated_at' => '2026-03-30 17:32:10',
            ],
            [
                'id' => 167,
                'name' => 'Paseh - Pimpinan',
                'email' => '320429.pimpinan@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$doFXJQUqDbpJejPPz4Q5fu4v3lC1dMVfrZgPDF/GjVB.00JdV2Lli',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:37',
                'updated_at' => '2026-03-30 17:32:10',
            ],
            [
                'id' => 168,
                'name' => 'Paseh - Bendahara',
                'email' => '320429.bendahara@kencana.id',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$ccf65qbqxXg6.pPMyUtvVeebapd0ad3pcAFr2JdzNhy/EjvwQsfBu',
                'remember_token' => NULL,
                'created_at' => '2026-03-30 17:25:38',
                'updated_at' => '2026-03-30 17:32:10',
            ],
        ]);
    }
}
